<?php
# MetInfo Enterprise Content Management System 
# Copyright (C) MetInfo Co.,Ltd (http://www.metinfo.cn). All rights reserved.

defined('IN_MET') or exit('No permission');

define ('TEM_INSTALL_VER', '1.000');

class install {
	function dosql(){
		global $_M;		
		
$sql = array (
  0 => 'pos =\'0\',no_order=\'1\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'顶部设置\',tips=\'\'',
  1 => 'pos =\'2\',no_order=\'1\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'文章模块\',tips=\'\'',
  2 => 'pos =\'3\',no_order=\'1\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'文章模块相关文章\',tips=\'\'',
  3 => 'pos =\'1\',no_order=\'1\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'产品展示\',tips=\'\'',
  4 => 'pos =\'2\',no_order=\'2\',type=\'4\',style=\'3\',selectd=\'$M$标题+更新时间$T$1$M$标题+描述+更新时间$T$2$M$缩略图+标题+描述+更新时间$T$3\',name =\'met_module2_type\',value=\'\',defaultvalue=\'\',valueinfo =\'展示方式\',tips=\'\'',
  5 => 'pos =\'3\',no_order=\'2\',type=\'2\',style=\'3\',selectd=\'\',name =\'met_module2_related\',value=\'\',defaultvalue=\'\',valueinfo =\'相关文章标题\',tips=\'\'',
  6 => 'pos =\'0\',no_order=\'2\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'twitter_open\',value=\'\',defaultvalue=\'\',valueinfo =\'twitter开关\',tips=\'\'',
  7 => 'pos =\'1\',no_order=\'2\',type=\'6\',style=\'3\',selectd=\'\',name =\'product_id\',value=\'\',defaultvalue=\'\',valueinfo =\'调用内容\',tips=\'\'',
  8 => 'pos =\'3\',no_order=\'3\',type=\'2\',style=\'3\',selectd=\'\',name =\'met_module2_relatednum\',value=\'\',defaultvalue=\'\',valueinfo =\'相关文章调用条数\',tips=\'调用同栏目分类下的文章\'',
  9 => 'pos =\'0\',no_order=\'3\',type=\'3\',style=\'3\',selectd=\'\',name =\'twitter_url\',value=\'\',defaultvalue=\'\',valueinfo =\'链接地址\',tips=\'\'',
  10 => 'pos =\'1\',no_order=\'3\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_title\',value=\'\',defaultvalue=\'\',valueinfo =\'自定义标题\',tips=\'为空则采用内容所属栏目名称\'',
  11 => 'pos =\'2\',no_order=\'3\',type=\'2\',style=\'3\',selectd=\'\',name =\'newsbiao_more\',value=\'\',defaultvalue=\'\',valueinfo =\'了解更多文字\',tips=\'\'',
  12 => 'pos =\'3\',no_order=\'4\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'产品模块相关产品\',tips=\'\'',
  13 => 'pos =\'0\',no_order=\'4\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'linkedin_open\',value=\'\',defaultvalue=\'\',valueinfo =\'linkedin开关\',tips=\'\'',
  14 => 'pos =\'1\',no_order=\'4\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_x\',value=\'\',defaultvalue=\'\',valueinfo =\'图片宽度\',tips=\'\'',
  15 => 'pos =\'2\',no_order=\'4\',type=\'2\',style=\'3\',selectd=\'\',name =\'newside_title\',value=\'\',defaultvalue=\'\',valueinfo =\'侧栏标题\',tips=\'侧栏二级栏目大标题\'',
  16 => 'pos =\'3\',no_order=\'5\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_related_title\',value=\'\',defaultvalue=\'\',valueinfo =\'相关产品标题\',tips=\'\'',
  17 => 'pos =\'0\',no_order=\'5\',type=\'3\',style=\'3\',selectd=\'\',name =\'linkedin_url\',value=\'\',defaultvalue=\'\',valueinfo =\'链接地址\',tips=\'\'',
  18 => 'pos =\'1\',no_order=\'5\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_y\',value=\'\',defaultvalue=\'\',valueinfo =\'图片高度\',tips=\'\'',
  19 => 'pos =\'2\',no_order=\'5\',type=\'2\',style=\'3\',selectd=\'\',name =\'met_module2_word\',value=\'\',defaultvalue=\'\',valueinfo =\'侧栏标题字数限制\',tips=\'\'',
  20 => 'pos =\'2\',no_order=\'6\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'产品模块\',tips=\'\'',
  21 => 'pos =\'3\',no_order=\'6\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_related_num\',value=\'\',defaultvalue=\'\',valueinfo =\'相关产品调用条数\',tips=\'调用同栏目分类下的产品\'',
  22 => 'pos =\'0\',no_order=\'6\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'facebook_open\',value=\'\',defaultvalue=\'\',valueinfo =\'facebook开关\',tips=\'\'',
  23 => 'pos =\'1\',no_order=\'6\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_num\',value=\'\',defaultvalue=\'\',valueinfo =\'显示条数\',tips=\'\'',
  24 => 'pos =\'2\',no_order=\'7\',type=\'4\',style=\'3\',selectd=\'缩略图+产品名称$T$1$M$缩略图+产品名称+描述$T$2$M$\',name =\'met_module3_type\',value=\'\',defaultvalue=\'\',valueinfo =\'展示方式\',tips=\'\'',
  25 => 'pos =\'0\',no_order=\'7\',type=\'3\',style=\'3\',selectd=\'\',name =\'facebook_url\',value=\'\',defaultvalue=\'\',valueinfo =\'链接地址\',tips=\'\'',
  26 => 'pos =\'1\',no_order=\'7\',type=\'4\',style=\'3\',selectd=\'$M$推荐产品$T$com$M$全部产品$T$\',name =\'product_type\',value=\'\',defaultvalue=\'\',valueinfo =\'调用类型\',tips=\'产品调用类型，【推荐产品】可以在添加或管理产品时设置。\'',
  27 => 'pos =\'3\',no_order=\'7\',type=\'2\',style=\'3\',selectd=\'\',name =\'proxx_num\',value=\'\',defaultvalue=\'\',valueinfo =\'简述字数\',tips=\'产品详情页简述字数\'',
  28 => 'pos =\'0\',no_order=\'8\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'google_open\',value=\'\',defaultvalue=\'\',valueinfo =\'google开关\',tips=\'\'',
  29 => 'pos =\'3\',no_order=\'8\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'solution\',tips=\'\'',
  30 => 'pos =\'1\',no_order=\'8\',type=\'4\',style=\'3\',selectd=\'$M$显示区块$T$1$M$隐藏区块$T$0\',name =\'product_open\',value=\'\',defaultvalue=\'\',valueinfo =\'区块开关\',tips=\'\'',
  31 => 'pos =\'2\',no_order=\'8\',type=\'6\',style=\'4\',selectd=\'\',name =\'proce_id\',value=\'\',defaultvalue=\'\',valueinfo =\'栏目选择\',tips=\'产品侧栏栏目选择\'',
  32 => 'pos =\'3\',no_order=\'9\',type=\'2\',style=\'3\',selectd=\'\',name =\'so_x\',value=\'\',defaultvalue=\'\',valueinfo =\'解决方案图片宽度\',tips=\'大图尺寸\'',
  33 => 'pos =\'0\',no_order=\'9\',type=\'3\',style=\'3\',selectd=\'\',name =\'google_url\',value=\'\',defaultvalue=\'\',valueinfo =\'链接地址\',tips=\'\'',
  34 => 'pos =\'1\',no_order=\'9\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_more\',value=\'\',defaultvalue=\'\',valueinfo =\'更多链接文字\',tips=\'\'',
  35 => 'pos =\'2\',no_order=\'9\',type=\'2\',style=\'3\',selectd=\'\',name =\'proce_num\',value=\'\',defaultvalue=\'\',valueinfo =\'显示数量\',tips=\'\'',
  36 => 'pos =\'3\',no_order=\'10\',type=\'2\',style=\'3\',selectd=\'\',name =\'so_y\',value=\'\',defaultvalue=\'\',valueinfo =\'解决方案图片高度\',tips=\'大图尺寸\'',
  37 => 'pos =\'0\',no_order=\'10\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'youtube_open\',value=\'\',defaultvalue=\'\',valueinfo =\'youtube开关\',tips=\'\'',
  38 => 'pos =\'1\',no_order=\'10\',type=\'6\',style=\'4\',selectd=\'\',name =\'product1_id\',value=\'\',defaultvalue=\'\',valueinfo =\'栏目1选择\',tips=\'\'',
  39 => 'pos =\'0\',no_order=\'11\',type=\'3\',style=\'3\',selectd=\'\',name =\'youtube_url\',value=\'\',defaultvalue=\'\',valueinfo =\'链接地址\',tips=\'\'',
  40 => 'pos =\'3\',no_order=\'11\',type=\'2\',style=\'3\',selectd=\'\',name =\'so_bot_title\',value=\'\',defaultvalue=\'\',valueinfo =\'底部数组标题\',tips=\'底部数组标题\'',
  41 => 'pos =\'1\',no_order=\'11\',type=\'7\',style=\'3\',selectd=\'\',name =\'product1_img\',value=\'\',defaultvalue=\'\',valueinfo =\'大图1\',tips=\'\'',
  42 => 'pos =\'2\',no_order=\'12\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'图片模块\',tips=\'\'',
  43 => 'pos =\'1\',no_order=\'12\',type=\'6\',style=\'4\',selectd=\'\',name =\'product2_id\',value=\'\',defaultvalue=\'\',valueinfo =\'栏目2选择\',tips=\'\'',
  44 => 'pos =\'3\',no_order=\'12\',type=\'2\',style=\'3\',selectd=\'\',name =\'so_bot_num\',value=\'\',defaultvalue=\'\',valueinfo =\'显示数量\',tips=\'\'',
  45 => 'pos =\'0\',no_order=\'12\',type=\'4\',style=\'3\',selectd=\'显示$T$1$M$隐藏$T$2$M$\',name =\'pinterest_open\',value=\'\',defaultvalue=\'\',valueinfo =\'腾讯开关\',tips=\'\'',
  46 => 'pos =\'2\',no_order=\'13\',type=\'4\',style=\'3\',selectd=\'$M$缩略图+名称$T$1$M$缩略图+名称+描述$T$2\',name =\'met_module5_type\',value=\'\',defaultvalue=\'\',valueinfo =\'展示方式\',tips=\'\'',
  47 => 'pos =\'1\',no_order=\'13\',type=\'7\',style=\'3\',selectd=\'\',name =\'product2_img\',value=\'\',defaultvalue=\'\',valueinfo =\'大图2\',tips=\'\'',
  48 => 'pos =\'0\',no_order=\'13\',type=\'3\',style=\'3\',selectd=\'\',name =\'pinterest_url\',value=\'\',defaultvalue=\'\',valueinfo =\'腾讯地址\',tips=\'\'',
  49 => 'pos =\'3\',no_order=\'13\',type=\'2\',style=\'3\',selectd=\'\',name =\'so_bot_y\',value=\'\',defaultvalue=\'\',valueinfo =\'图片高度\',tips=\'\'',
  50 => 'pos =\'2\',no_order=\'14\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'页面文字\',tips=\'\'',
  51 => 'pos =\'0\',no_order=\'14\',type=\'2\',style=\'3\',selectd=\'\',name =\'LogoTop\',value=\'\',defaultvalue=\'\',valueinfo =\'LOGO下偏移\',tips=\'细微调整LOGO位置\'',
  52 => 'pos =\'1\',no_order=\'14\',type=\'6\',style=\'4\',selectd=\'\',name =\'product3_id\',value=\'\',defaultvalue=\'\',valueinfo =\'栏目3选择\',tips=\'\'',
  53 => 'pos =\'3\',no_order=\'14\',type=\'2\',style=\'3\',selectd=\'\',name =\'sobots_title\',value=\'\',defaultvalue=\'\',valueinfo =\'底部标题\',tips=\'\'',
  54 => 'pos =\'2\',no_order=\'15\',type=\'2\',style=\'3\',selectd=\'\',name =\'gengduo\',value=\'\',defaultvalue=\'\',valueinfo =\'按钮文字\',tips=\'查看或了解更多文字\'',
  55 => 'pos =\'0\',no_order=\'15\',type=\'2\',style=\'3\',selectd=\'\',name =\'LogoLeft\',value=\'\',defaultvalue=\'\',valueinfo =\'LOGO右偏移\',tips=\'细微调整LOGO位置\'',
  56 => 'pos =\'1\',no_order=\'15\',type=\'7\',style=\'3\',selectd=\'\',name =\'product3_img\',value=\'\',defaultvalue=\'\',valueinfo =\'大图3\',tips=\'\'',
  57 => 'pos =\'3\',no_order=\'15\',type=\'3\',style=\'3\',selectd=\'\',name =\'sobots_desc\',value=\'\',defaultvalue=\'\',valueinfo =\'底部简述\',tips=\'\'',
  58 => 'pos =\'1\',no_order=\'16\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'图片滚动区\',tips=\'\'',
  59 => 'pos =\'3\',no_order=\'16\',type=\'7\',style=\'3\',selectd=\'\',name =\'sobots_img\',value=\'\',defaultvalue=\'\',valueinfo =\'底部图片\',tips=\'\'',
  60 => 'pos =\'0\',no_order=\'17\',type=\'3\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'banner_word\',value=\'\',defaultvalue=\'\',valueinfo =\'banner文字\',tips=\'\'',
  61 => 'pos =\'1\',no_order=\'17\',type=\'6\',style=\'3\',selectd=\'\',name =\'case_id\',value=\'\',defaultvalue=\'\',valueinfo =\'调用内容\',tips=\'\'',
  62 => 'pos =\'3\',no_order=\'17\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'联系我们\',tips=\'\'',
  63 => 'pos =\'0\',no_order=\'18\',type=\'3\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'banner_anniu\',value=\'\',defaultvalue=\'\',valueinfo =\'banner按钮文字\',tips=\'\'',
  64 => 'pos =\'1\',no_order=\'18\',type=\'2\',style=\'3\',selectd=\'\',name =\'case_title\',value=\'\',defaultvalue=\'\',valueinfo =\'自定义标题\',tips=\'为空则采用内容所属栏目名称\'',
  65 => 'pos =\'3\',no_order=\'18\',type=\'2\',style=\'3\',selectd=\'\',name =\'xxcon_title\',value=\'\',defaultvalue=\'\',valueinfo =\'联系我们标题\',tips=\'联系我们详细页标题\'',
  66 => 'pos =\'0\',no_order=\'19\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'xuhao\',value=\'\',defaultvalue=\'\',valueinfo =\'是否显示序号\',tips=\'banner标题后面的序号\'',
  67 => 'pos =\'1\',no_order=\'19\',type=\'3\',style=\'3\',selectd=\'\',name =\'case_desc\',value=\'\',defaultvalue=\'\',valueinfo =\'简短描述\',tips=\'\'',
  68 => 'pos =\'3\',no_order=\'19\',type=\'8\',style=\'3\',selectd=\'\',name =\'xxcon_content\',value=\'\',defaultvalue=\'\',valueinfo =\'联系我们内容\',tips=\'联系我们内容\'',
  69 => 'pos =\'1\',no_order=\'20\',type=\'4\',style=\'3\',selectd=\'推荐信息$T$com$M$所有信息$T$$M$\',name =\'case_type\',value=\'\',defaultvalue=\'\',valueinfo =\'调用类型\',tips=\'调用类型，【推荐】可以在添加或管理内容时设置。\'',
  70 => 'pos =\'0\',no_order=\'20\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'底部设置\',tips=\'\'',
  71 => 'pos =\'3\',no_order=\'20\',type=\'2\',style=\'3\',selectd=\'\',name =\'xxcon_biao_title\',value=\'\',defaultvalue=\'\',valueinfo =\'联系我们表格标题\',tips=\'联系我们表格标题\'',
  72 => 'pos =\'1\',no_order=\'21\',type=\'2\',style=\'3\',selectd=\'\',name =\'case_num\',value=\'\',defaultvalue=\'\',valueinfo =\'显示条数\',tips=\'\'',
  73 => 'pos =\'0\',no_order=\'21\',type=\'7\',style=\'3\',selectd=\'\',name =\'bottom_img\',value=\'\',defaultvalue=\'\',valueinfo =\'底部图片\',tips=\'\'',
  74 => 'pos =\'3\',no_order=\'21\',type=\'3\',style=\'3\',selectd=\'\',name =\'xxcon_online_desc\',value=\'\',defaultvalue=\'\',valueinfo =\'在线联系简述\',tips=\'\'',
  75 => 'pos =\'1\',no_order=\'22\',type=\'2\',style=\'3\',selectd=\'\',name =\'case_y\',value=\'\',defaultvalue=\'\',valueinfo =\'图片高度\',tips=\'\'',
  76 => 'pos =\'3\',no_order=\'22\',type=\'2\',style=\'3\',selectd=\'\',name =\'xxcon_online_anw\',value=\'\',defaultvalue=\'\',valueinfo =\'按钮文字\',tips=\'\'',
  77 => 'pos =\'1\',no_order=\'23\',type=\'2\',style=\'3\',selectd=\'\',name =\'case_x\',value=\'\',defaultvalue=\'\',valueinfo =\'图片宽度\',tips=\'\'',
  78 => 'pos =\'3\',no_order=\'23\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'下载模块详情页\',tips=\'\'',
  79 => 'pos =\'3\',no_order=\'24\',type=\'2\',style=\'3\',selectd=\'\',name =\'download_pwd_input_submit_btn_txt\',value=\'Submit\',defaultvalue=\'Submit\',valueinfo =\'下载详情页密码输入表单提交按钮文本\',tips=\'\'',
  80 => 'pos =\'1\',no_order=\'25\',type=\'4\',style=\'3\',selectd=\'$M$显示区块$T$1$M$隐藏区块$T$0\',name =\'case_open\',value=\'\',defaultvalue=\'\',valueinfo =\'区块开关\',tips=\'\'',
  81 => 'pos =\'3\',no_order=\'25\',type=\'2\',style=\'3\',selectd=\'\',name =\'download_pwd_input_placeholder\',value=\'enter password here\',defaultvalue=\'enter password here\',valueinfo =\'下载详情页密码输入框占位文本\',tips=\'\'',
  82 => 'pos =\'1\',no_order=\'26\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'解决方案\',tips=\'\'',
  83 => 'pos =\'3\',no_order=\'26\',type=\'2\',style=\'3\',selectd=\'\',name =\'download_pwd_input_desc\',value=\'This file is password protected, please enter password to download.\',defaultvalue=\'This file is password protected, please enter password to download.\',valueinfo =\'下载详情页密码输入说明\',tips=\'\'',
  84 => 'pos =\'1\',no_order=\'27\',type=\'6\',style=\'4\',selectd=\'\',name =\'solution_id\',value=\'\',defaultvalue=\'\',valueinfo =\'栏目选择\',tips=\'\'',
  85 => 'pos =\'1\',no_order=\'28\',type=\'2\',style=\'3\',selectd=\'\',name =\'solution_title\',value=\'\',defaultvalue=\'\',valueinfo =\'自定义标题\',tips=\'\'',
  86 => 'pos =\'1\',no_order=\'29\',type=\'3\',style=\'3\',selectd=\'\',name =\'solution_desc\',value=\'\',defaultvalue=\'\',valueinfo =\'简短描述\',tips=\'\'',
  87 => 'pos =\'1\',no_order=\'30\',type=\'2\',style=\'3\',selectd=\'\',name =\'solution_num\',value=\'\',defaultvalue=\'\',valueinfo =\'显示条数\',tips=\'\'',
  88 => 'pos =\'1\',no_order=\'31\',type=\'2\',style=\'3\',selectd=\'\',name =\'solution_x\',value=\'\',defaultvalue=\'\',valueinfo =\'图片宽度\',tips=\'\'',
  89 => 'pos =\'1\',no_order=\'32\',type=\'2\',style=\'3\',selectd=\'\',name =\'solution_y\',value=\'\',defaultvalue=\'\',valueinfo =\'图片高度\',tips=\'\'',
  90 => 'pos =\'1\',no_order=\'33\',type=\'7\',style=\'3\',selectd=\'\',name =\'solution_img\',value=\'\',defaultvalue=\'\',valueinfo =\'图片\',tips=\'\'',
  91 => 'pos =\'1\',no_order=\'34\',type=\'4\',style=\'3\',selectd=\'$M$显示区块$T$1$M$隐藏区块$T$0\',name =\'solution_open\',value=\'\',defaultvalue=\'\',valueinfo =\'区块开关\',tips=\'\'',
  92 => 'pos =\'1\',no_order=\'35\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'关于我们\',tips=\'\'',
  93 => 'pos =\'1\',no_order=\'36\',type=\'2\',style=\'3\',selectd=\'\',name =\'about_title\',value=\'\',defaultvalue=\'\',valueinfo =\'标题\',tips=\'\'',
  94 => 'pos =\'1\',no_order=\'37\',type=\'3\',style=\'3\',selectd=\'\',name =\'about_desc\',value=\'\',defaultvalue=\'\',valueinfo =\'简短描述\',tips=\'\'',
  95 => 'pos =\'1\',no_order=\'38\',type=\'6\',style=\'4\',selectd=\'\',name =\'about_id\',value=\'\',defaultvalue=\'\',valueinfo =\'图片栏目选择\',tips=\'建议选择公司新闻栏目。\'',
  96 => 'pos =\'1\',no_order=\'39\',type=\'2\',style=\'3\',selectd=\'\',name =\'about_num\',value=\'\',defaultvalue=\'\',valueinfo =\'图片数量\',tips=\'\'',
  97 => 'pos =\'1\',no_order=\'40\',type=\'2\',style=\'3\',selectd=\'\',name =\'about_contitle\',value=\'\',defaultvalue=\'\',valueinfo =\'文章标题\',tips=\'\'',
  98 => 'pos =\'1\',no_order=\'41\',type=\'8\',style=\'3\',selectd=\'\',name =\'about_content\',value=\'\',defaultvalue=\'\',valueinfo =\'简介内容\',tips=\'\'',
  99 => 'pos =\'1\',no_order=\'42\',type=\'6\',style=\'4\',selectd=\'\',name =\'abous_id\',value=\'\',defaultvalue=\'\',valueinfo =\'栏目2选择\',tips=\'\'',
  100 => 'pos =\'1\',no_order=\'43\',type=\'2\',style=\'3\',selectd=\'\',name =\'abous_num\',value=\'\',defaultvalue=\'\',valueinfo =\'栏目调用数量\',tips=\'\'',
  101 => 'pos =\'1\',no_order=\'44\',type=\'7\',style=\'3\',selectd=\'\',name =\'about_bgimg\',value=\'\',defaultvalue=\'\',valueinfo =\'背景图片\',tips=\'\'',
  102 => 'pos =\'1\',no_order=\'45\',type=\'4\',style=\'3\',selectd=\'$M$显示区块$T$1$M$隐藏区块$T$0\',name =\'about_open\',value=\'\',defaultvalue=\'\',valueinfo =\'区块开关\',tips=\'\'',
  103 => 'pos =\'1\',no_order=\'46\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'文章列表设置\',tips=\'\'',
  104 => 'pos =\'1\',no_order=\'47\',type=\'6\',style=\'4\',selectd=\'\',name =\'news_id\',value=\'\',defaultvalue=\'\',valueinfo =\'栏目选择\',tips=\'\'',
  105 => 'pos =\'1\',no_order=\'48\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_title\',value=\'\',defaultvalue=\'\',valueinfo =\'大标题\',tips=\'\'',
  106 => 'pos =\'1\',no_order=\'49\',type=\'3\',style=\'3\',selectd=\'\',name =\'news_desc\',value=\'\',defaultvalue=\'\',valueinfo =\'简短描述\',tips=\'\'',
  107 => 'pos =\'1\',no_order=\'50\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_num\',value=\'\',defaultvalue=\'\',valueinfo =\'显示条数\',tips=\'文章列表显示条数\'',
  108 => 'pos =\'1\',no_order=\'51\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_x\',value=\'\',defaultvalue=\'\',valueinfo =\'图片宽度\',tips=\'\'',
  109 => 'pos =\'1\',no_order=\'52\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_y\',value=\'\',defaultvalue=\'\',valueinfo =\'图片高度\',tips=\'\'',
  110 => 'pos =\'1\',no_order=\'53\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_more\',value=\'\',defaultvalue=\'\',valueinfo =\'更多链接文字\',tips=\'链接到对应栏目的列表页\'',
  111 => 'pos =\'1\',no_order=\'54\',type=\'4\',style=\'3\',selectd=\'显示区块$T$1$M$隐藏区块$T$0$M$\',name =\'news_open\',value=\'\',defaultvalue=\'\',valueinfo =\'区块开关\',tips=\'\'',
  112 => 'pos =\'1\',no_order=\'55\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'客户见证\',tips=\'\'',
  113 => 'pos =\'1\',no_order=\'56\',type=\'6\',style=\'3\',selectd=\'\',name =\'customer_id\',value=\'\',defaultvalue=\'\',valueinfo =\'栏目选择\',tips=\'\'',
  114 => 'pos =\'1\',no_order=\'57\',type=\'2\',style=\'3\',selectd=\'\',name =\'customer_title\',value=\'\',defaultvalue=\'\',valueinfo =\'标题\',tips=\'\'',
  115 => 'pos =\'1\',no_order=\'58\',type=\'3\',style=\'3\',selectd=\'\',name =\'customer_desc\',value=\'\',defaultvalue=\'\',valueinfo =\'简短描述\',tips=\'\'',
  116 => 'pos =\'1\',no_order=\'59\',type=\'2\',style=\'3\',selectd=\'\',name =\'customer_num\',value=\'\',defaultvalue=\'\',valueinfo =\'显示数量\',tips=\'\'',
  117 => 'pos =\'1\',no_order=\'60\',type=\'4\',style=\'3\',selectd=\'$M$显示区块$T$1$M$隐藏区块$T$0\',name =\'customer_open\',value=\'\',defaultvalue=\'\',valueinfo =\'区块开关\',tips=\'\'',
  118 => 'pos =\'1\',no_order=\'61\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'邮件区块\',tips=\'\'',
  119 => 'pos =\'1\',no_order=\'62\',type=\'7\',style=\'3\',selectd=\'\',name =\'emo_img\',value=\'\',defaultvalue=\'\',valueinfo =\'背景上方图片\',tips=\'\'',
  120 => 'pos =\'1\',no_order=\'64\',type=\'7\',style=\'3\',selectd=\'\',name =\'emt_img\',value=\'\',defaultvalue=\'\',valueinfo =\'背景图片\',tips=\'\'',
  121 => 'pos =\'1\',no_order=\'65\',type=\'2\',style=\'3\',selectd=\'\',name =\'con_title\',value=\'\',defaultvalue=\'\',valueinfo =\'左边标题\',tips=\'\'',
  122 => 'pos =\'1\',no_order=\'66\',type=\'3\',style=\'3\',selectd=\'\',name =\'con_desc\',value=\'\',defaultvalue=\'\',valueinfo =\'详细地址\',tips=\'\'',
  123 => 'pos =\'1\',no_order=\'67\',type=\'2\',style=\'3\',selectd=\'\',name =\'con_tel\',value=\'\',defaultvalue=\'\',valueinfo =\'电话\',tips=\'\'',
  124 => 'pos =\'1\',no_order=\'68\',type=\'3\',style=\'3\',selectd=\'\',name =\'con_net\',value=\'\',defaultvalue=\'\',valueinfo =\'网址\',tips=\'\'',
  125 => 'pos =\'1\',no_order=\'69\',type=\'2\',style=\'3\',selectd=\'\',name =\'share_title\',value=\'\',defaultvalue=\'\',valueinfo =\'分享标题\',tips=\'\'',
  126 => 'pos =\'1\',no_order=\'70\',type=\'4\',style=\'3\',selectd=\'$M$显示区块$T$1$M$隐藏区块$T$0\',name =\'email_open\',value=\'\',defaultvalue=\'\',valueinfo =\'区块开关\',tips=\'\'',
  127 => 'pos =\'1\',no_order=\'71\',type=\'2\',style=\'3\',selectd=\'\',name =\'mass_title\',value=\'\',defaultvalue=\'\',valueinfo =\'反馈标题\',tips=\'\'',
);
$no='goken';
$devices='0';
		$re['sql'] = $sql;
		$re['no'] = $no;
		$re['devices'] = $devices;
		return $re;
	}
}

# This program is an open source system, commercial use, please consciously to purchase commercial license.
# Copyright (C) MetInfo Co., Ltd. (http://www.metinfo.cn). All rights reserved.
?>